Added literature for advanced edge detection techniques for underwater applications and image enhancement techniques for underwater data
UCSD-E4E/fishsense pull request #5
Opened 2023-08-01 00:37 UTC by HJGrant

2023-08-01 05:36 UTC, ntlhui requested changes

2023-08-01 05:36 UTC, ntlhui commented on references/fishsense.bib
> +  file    = {:C\:/Users/Hamish/Downloads/Object_Detection_in_Underwater_Image_by_Detecting_Edges_using_Adaptive_Thresholding.pdf:PDF},
@ccrutchf how do we want to handle files?

2023-08-01 05:36 UTC, ntlhui commented on references/fishsense.bib
> +  file    = {:C\:/Users/Hamish/Downloads/An_In-Depth_Survey_of_Underwater_Image_Enhancement_and_Restoration.pdf:PDF},
Local file!

2023-08-01 05:36 UTC, ntlhui commented on references/fishsense.bib
> +  file    = {:C\:/Users/Hamish/Downloads/A_retinex-based_enhancing_approach_for_single_underwater_image.pdf:PDF},
Local file!

2023-08-01 17:37 UTC, HJGrant commented
I've removed the lines that contained the local file paths. I had them in there so that I could find my files through the JabRef software.

2023-08-01 17:43 UTC, ntlhui commented
@ccrutchf please establish the policy for how you want to store the PDF files

2023-08-09 19:00 UTC, merged

2023-08-09 19:00 UTC, ntlhui approved these changes